#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="argonaut"

check_service_initialized init 20-php-fpm

#### Disable or Enable Argonaut Server from Starting
if var_true $ENABLE_ARGONAUT ;  then
  print_notice "Enabling Argonaut Server"
else
  service_stop 30-argonaut
fi

liftoff