#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/00-container-initialized ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nginx ]; then

### Force Reset Permissions for Security
  chown -R nginx:www-data /www/fusiondirectory

### Start nginx
  mkdir -p /www/logs/nginx
  mkdir -p /www/logs/smtp
  mkdir -p /tmp/nginx
  chown -R nginx /www/logs/nginx
  chown -R nginx /www/logs/smtp
  chown nginx /tmp/nginx
  mkdir -p /tmp/state
  echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo '**'
echo '** Starting FusionDirectory..'
exec nginx
