#!/usr/bin/with-contenv bash

for s in /assets/functions/*; do source $s; done
PROCESS_NAME="argonaut"

check_container_initialized
check_service_initialized init
liftoff

print_info "Starting Argonaut Server ${ARGONAUT_VERSION}"
exec argonaut-server
