#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/30-fusiondirectory-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/30-argonaut ]; then
  echo 'Initialization Complete' >/tmp/state/30-argonaut
fi

echo "** [fusiondirectory] Starting Argonaut Server ${ARGONAUT_VERSION}"
exec argonaut-server
