services:
  
  fusiondirectory-app:
    container_name: fusiondirectory-app
    image: fusiondirectory
    labels:
      - traefik.enable=true
      - traefik.http.routers.fusiondirectory-app.rule=Host(`fusiondirectory.example.com`)
      - traefik.http.services.fusiondirectory-app.loadbalancer.server.port=80
    volumes:
      - ./logs:/www/logs
      #- ./custom:/assets/fusiondirectory
      #- ./plugins-custom:/assets/plugins-custom
    environment:
      - TIMEZONE=America/Vancouver
      - CONTAINER_NAME=fusiondirectory-app

      - ENABLE_ARGONAUT=FALSE
      - PLUGIN_AUDIT=TRUE
      - PLUGIN_DSA=TRUE
      - PLUGIN_LDAPDUMP=TRUE
      - PLUGIN_LDAPMANAGER=TRUE
      - PLUGIN_MAIL=TRUE
      - PLUGIN_PERSONAL=TRUE
      - PLUGIN_PPOLICY=TRUE
      - PLUGIN_SSH=TRUE
      - PLUGIN_SUDO=TRUE
      - PLUGIN_WEBSERVICE=TRUE

      - LDAP01_HOST=openldap-fusiondirectory
      - LDAP01_BASE_DN=dc=example,dc=org
      - LDAP01_ADMIN_DN=cn=admin,dc=example,dc=org
      - LDAP01_ADMIN_PASS=admin
      - LDAP01_PORT=389
      - LDAP01_NAME=Production

     #- LDAP02_BASE_DN=dc=example,dc=org
     #- LDAP02_ADMIN_DN=cn=admin,dc=example,dc=org
     #- LDAP02_HOST=openldap-fusiondirectory2
     #- LDAP02_ADMIN_PASS=password2
     #- LDAP02_NAME=Development
     #- LDAP02_TLS=TRUE
    networks:
      - proxy
      - services
    restart: always

networks:
  proxy:
    external: true
  services:
    external: true

