#!/usr/bin/with-contenv bash

  ### Adjust NGINX Runtime Variables
  UPLOAD_MAX_SIZE=${UPLOAD_MAX_SIZE:="2G"}
  PHP_TIMEOUT=${PHP_TIMEOUT:-"600"}
  sed -i -e "s/<UPLOAD_MAX_SIZE>/$UPLOAD_MAX_SIZE/g" /etc/nginx/nginx.conf
  sed -i -e "s/<PHP_TIMEOUT>/$PHP_TIMEOUT/g" /etc/nginx/conf.d/default.conf
  
### FusionDirectory
  ### Sanity Test, Set Default Environment Variables
  LDAP_ADMIN_PASSWORD=${LDAP_ENV_LDAP_ADMIN_PASSWORD:-${LDAP_ADMIN_PASSWORD}}
  LDAP_COMM_PORT=${LDAP_COMM_PORT:-389}
  LDAP_DOMAIN=${LDAP_ENV_LDAP_DOMAIN:-${LDAP_DOMAIN}}
  LDAP_HOST=${LDAP_PORT_389_TCP_ADDR:-${LDAP_HOST}}
  LDAP_SCHEME=${LDAP_SCHEME:-"ldap"}
  LDAP_TLS=${LDAP_TLS:-"false"}
  LDAP_TLS=${LDAP_ENV_LDAP_TLS:-${LDAP_TLS}}

### Configuration File Building
  if [ -z ${LDAP_DOMAIN} ] ; then printf "\n\n** [fusiondirectory] LDAP_DOMAIN is not defined - Please set to proceed\n"; exit 1; fi;
  if [ -z ${LDAP_HOST} ] ; then printf "\n\n** [fusiondirectory] LDAP_HOST is not defined - Please set to proceed\n"; exit 1; fi;
  if [ -z ${LDAP_ADMIN_PASSWORD} ] ; then printf "\n\n** [fusiondirectory] LDAP_ADMIN_PASSWORD is not defined - Please set to proceed\n"; exit 1; fi;

  IFS='.' read -a domain_elems <<< "${LDAP_DOMAIN}"

  suffix=""
  for elem in "${domain_elems[@]}" ; do
      if [ "x${suffix}" = x ] ; then
          suffix="dc=${elem}"
      else
          suffix="${suffix},dc=${elem}"
      fi
  done

  if [ -z ${LDAP_ADMIN_DN} ] ; then
      BASE_DN="dc=$(echo ${LDAP_DOMAIN} | sed 's/^\.//; s/\.$//; s/\./,dc=/g')"
      : ${LDAP_ADMIN:="admin"}
      LDAP_ADMIN_DN="cn=${LDAP_ADMIN},${BASE_DN}"
      echo "** LDAP_ADMIN_DN is not defined and set to '${LDAP_ADMIN_DN}'"
  fi

  if ${LDAP_TLS}; then
      LDAP_SCHEME="ldaps"
      LDAP_COMM_PORT=636
  fi

  
### Write Fusiondirectory Configuration
  cat <<EOF > /etc/fusiondirectory/fusiondirectory.conf
<?xml version="1.0"?>
<conf>
  <!-- Main section **********************************************************
       The main section defines global settings, which might be overridden by
       each location definition inside.

       For more information about the configuration parameters, take a look at
       the FusionDirectory.conf(5) manual page.
  -->
  <main default="${INSTANCE}"
        logging="TRUE"
        displayErrors="FALSE"
        forceSSL="FALSE"
        templateCompileDirectory="/var/spool/fusiondirectory/"
        debugLevel="0"
    >

    <!-- Location definition -->
    <location name="${INSTANCE}"
    >
        <referral URI="${LDAP_SCHEME}://${LDAP_HOST}:${LDAP_COMM_PORT}/${suffix}"
                        adminDn="${LDAP_ADMIN_DN}"
                        adminPassword="${LDAP_ADMIN_PASSWORD}" />
    </location>
  </main>
</conf>
EOF

	chmod 640 /etc/fusiondirectory/fusiondirectory.conf
	chown root:www-data /etc/fusiondirectory/fusiondirectory.conf
	yes Yes | fusiondirectory-setup --check-config 

  ### Theme Support
  if [ -d /assets/fusiondirectory ] ; then
     echo "Custom HTML Found, Copying over top of Master.."
     cp -R /assets/fusiondirectory/* /www/html/fusiondirectory/
  fi

  mkdir -p /tmp/state
  touch /tmp/state/10-nginx-init

