#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/00-container-initialized ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nginx ]; then

### Force Reset Permissions for Security
  chown -R nginx:www-data /www/fusiondirectory

### Start nginx
  mkdir -p /tmp/state
  echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo '**'
echo '** [fusiondirectory] Starting Nginx'
exec nginx
