#!/usr/bin/with-contenv bash

while [ ! -f /tmp/state/10-nginx-init ]
do
  sleep 1
done

if [ ! -f /tmp/state/10-nginx ]; then

### Start nginx
  mkdir -p /www/logs/nginx
  mkdir -p /tmp/nginx
  chown -R www-data /www/logs/nginx
  chown www-data /tmp/nginx
  mkdir -p /tmp/state
  echo 'Initialization Complete' >/tmp/state/10-nginx
fi

echo '**'
echo '** Starting FusionDirectory'
exec nginx
